name: Process HTML Files

on:
  push:
    paths:
      - 'upload/**'

jobs:
  process-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Process files
      run: |
        python update_urls.py
        
    - name: Upload processed files
      uses: actions/upload-artifact@v3
      with:
        name: processed-files
        path: processed/
        
    - name: Commit processed files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add processed/
        git commit -m "Automatically processed HTML files" || echo "No changes to commit"
        git push
