name: Process HTML Files

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'YES' to confirm processing"
        required: true
        default: "NO"

jobs:
  process-files:
    if: github.event.inputs.confirm == 'YES'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Process files
      run: |
        python update_urls.py
        
    - name: Create artifact timestamp
      id: timestamp
      run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
        
    - name: Upload processed files
      uses: actions/upload-artifact@v4
      with:
        name: processed-files-${{ steps.timestamp.outputs.timestamp }}
        path: processed/
        retention-days: 7
        
    - name: Commit processed files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add processed/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automatically processed HTML files [skip ci]" && git push)
